apiVersion: v1
kind: Service
metadata:
  name: mongo-test
  labels:
    run: mongo-test
spec:
#  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017 
    protocol: TCP
    name: mongo
  selector:
    run: mongo-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-test
spec:
  selector:
    matchLabels:
      run: mongo-test
  replicas: 1
  template:
    metadata:
      labels:
        run: mongo-test
    spec:
      containers:
      - name: mongodb
        image: docker.io/mongo
        ports:
        - containerPort: 27017
      nodeSelector:
        location: houston
